### ISSUE TITLE
Styling af forside

### ISSUE THREAD

**Issue by jonasdk** [PeterStub/nowbase#1]
# Hvor ligger det
http://nowbase.org/da

# Screenshots
<img width="1153" alt="frontpage - nowbase" src="https://user-images.githubusercontent.com/85319/34417917-6114bdf6-ebfb-11e7-88e7-e105bac02a61.png">
<img width="320" alt="frontpage - nowbase" src="https://user-images.githubusercontent.com/85319/34417922-667de0a6-ebfb-11e7-9b46-17ba9fbcfed8.png">

**Comment by PeterStub** [comment]
Tror den er OK
