### ISSUE TITLE
Sharethis

### ISSUE THREAD

**Issue by PeterStub** [PeterStub/nowbase#25]
Heysan - har indsat en Sharethis - det er en block. Har placeret den i region Breadcrumb - ved ikke om det virker?

Er det noget du kan løse?
![share](https://user-images.githubusercontent.com/479000/35485506-eb39f23a-0460-11e8-9b63-98c557bbac0d.png)

**Comment by jonasdk** [comment]
Yepper den ser jeg på

**Comment by jonasdk** [comment]
Yepper den ser jeg på
