### ISSUE TITLE
Content af typen accordion

### ISSUE THREAD

**Issue by jonasdk** [PeterStub/nowbase#7]
# Beskrivelse
På Nowbases nuværende site er der en del sider med lister som foldes ud til et form for accordion, dem vil jeg umiddelbart løse som dl-lister (description list med dt og dd som scriptet kører på) medmindre det er indhold som kommer andet sted fra. Dvs. hvis det er data som de selv smider i sitet så vil jeg gerne at I lige finder en løsning så de kan lave dem selv nemt.

# Screenshots
<img width="940" alt="screen shot 2018-01-14 at 23 58 46" src="https://user-images.githubusercontent.com/85319/34921835-7150ea20-f987-11e7-8230-244edef8b336.png">
<img width="914" alt="screen shot 2018-01-14 at 23 58 52" src="https://user-images.githubusercontent.com/85319/34921836-7303b69a-f987-11e7-85ce-9ac6551cc817.png">

**Comment by PeterStub** [comment]
Den er løst OK for nu - dog animere krydset ikke - men lad os se om de opdager det...
