### ISSUE TITLE
menuer under punkter med kun et punkt

### ISSUE THREAD

**Issue by jonasdk** [PeterStub/nowbase#9]
Når jeg kigger på en side som http://nowbase.sweetlemon.dk/database er problemet at der ikke er en menu - derfor falder siden sammen til venstre. Hvis jeg kigge på den tilsvarende på det nuværende site er der en menu med et punkt ude til venstre. 

Derfor vil jeg hører om det er noget du opretter eller noget jeg skal?

**Comment by PeterStub** [comment]
Vi bruger ikke menu'er på solo sider - altså sider der ikke bor i en menu...
